version: '3.0'
services:
  rabbitmq:
    image: rabbitmq:3.10.2
    hostname: "myRabbit"
    container_name: "rabbitmq"
    volumes:
      - v $pwd/data:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_VHOST=my_vhost
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - fcf_net
    restart: on-failure

  redis:
    image: redis:latest
    container_name: "redis"
    restart: always
    ports:
      - 6379:6379
    networks:
      - fcf_net
    volumes:
      - ./redis/conf/redis.conf:/etc/redis/redis.conf:rw
      - ./redis/data:/data:rw
    command:
      redis-server /etc/redis/redis.conf --appendonly yes --requirepass 123456

  elasticsearch:
    image: elasticsearch:7.12.1
    hostname: "elasticsearch"
    container_name: "elasticsearch"
    restart: on-failure
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS="-Xms84m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - fcf_net

  skywalking-oap-server:
    image: apache/skywalking-oap-server:8.9.1
    container_name: "skywalking-oap-server"
    hostname: "skywalking-oap-server"
    restart: on-failure
    environment:
      - SW_STORAGE=elasticsearch
      - SW_STORAGE_ES_CLUSTER_NODES=elasticsearch:9200
    ports:
      - 11800:11800
      - 12800:12800
    depends_on:
      - elasticsearch
    networks:
      - fcf_net

  skywalking-ui:
    image: apache/skywalking-ui:8.9.1
    container_name: "skywalking-ui"
    restart: on-failure
    environment:
      - SW_OAP_ADDRESS=http://skywalking-oap-server:12800
    ports:
      - 8081:8080
    depends_on:
      - skywalking-oap-server
    networks:
      - fcf_net

networks:
  fcf_net:
    driver: bridge