version: '3.0'
services:
  rabbitmq:
    image: rabbitmq:3.10.2
    hostname: "myRabbit"
    container_name: "rabbitmq"
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_VHOST=my_vhost
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - fcf_net
    restart: on-failure

  redis:
    image: redis:latest
    container_name: "redis"
    restart: always
    ports:
      - 6379:6379
    networks:
      - fcf_net
    volumes:
      - ./redis/conf/redis.conf:/etc/redis/redis.conf:rw
      - ./redis/data:/data:rw
    command:
      redis-server /etc/redis/redis.conf --appendonly yes --requirepass 123456
  mysql:
    image: mysql:8.0.29
    container_name: "mysql"
    restart: always
    ports:
      - 3306:3306
    networks:
      - fcf_net
    volumes:
      - ./mysql/conf/:/etc/mysql/conf.d:rw
      - ./mysql/logs/:/logs
      - ./mysql/data/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --lower_case_table_names=1

  xxl-job:
    image: xuxueli/xxl-job-admin:2.3.1
    container_name: "xxl-job-admin"
    restart: always
    ports:
      # 暴露外面的：内部的
      - 8892:8080
    volumes:
      - ./xxl-job/:/data/applogs:rw
    networks:
      - fcf_net
    depends_on:
      - mysql
    environment:
      - PARAMS=--spring.datasource.username=root --spring.datasource.password=root --spring.datasource.url=jdbc:mysql://mysql:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai

networks:
  fcf_net:
    driver: bridge